//! A page: a document, a JS context, and the loop that runs one until it stops
//! changing.

use crate::dom::SharedDoc;
use crate::natives;
use crate::net::NetworkProvider;
use crate::state::{ConsoleMessage, Limits, Navigation, PageState, ScriptError, Shared, shared};
use mar_dom::{Document, LocalName, NodeId};
use rquickjs::{CatchResultExt, Context, Ctx, Function, Module, Persistent, Runtime};
use std::rc::Rc;
use std::time::{Duration, Instant};
use url::Url;

const PRELUDE: &str = include_str!("prelude.js");
/// The same, compiled by `build.rs`. See there for why.
const PRELUDE_BYTECODE: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/prelude.qjsbc"));

/// Run the prelude: the bytecode when it loads, the source when it does not.
///
/// The bytecode was produced by this build from this source, so the
/// fallback is for a build that somehow disagrees with itself, not a path
/// anything is expected to take.
fn run_prelude(ctx: &Ctx<'_>) -> Result<(), String> {
    // SAFETY: the bytes come from `Module::write` in this crate's build
    // script, against the same QuickJS this binary links.
    let loaded = unsafe { Module::load(ctx.clone(), PRELUDE_BYTECODE) };
    if let Ok(module) = loaded
        && let Ok((_, promise)) = module.eval()
    {
        // The module imports nothing, so its body has already run; the
        // promise holds the exception if it threw.
        return match promise.result::<()>() {
            Some(outcome) => outcome
                .catch(ctx)
                .map(|_| ())
                .map_err(|e| format!("prelude: {e}")),
            None => Ok(()),
        };
    }
    tracing::warn!("prelude bytecode did not load; evaluating the source instead");
    // catch() turns the opaque "Exception generated by QuickJS" into the
    // actual message and stack.
    ctx.eval::<(), _>(PRELUDE)
        .catch(ctx)
        .map(|_| ())
        .map_err(|e| format!("prelude: {e}"))
}

#[derive(Debug, thiserror::Error)]
pub enum PageError {
    #[error("javascript engine error: {0}")]
    Engine(String),
    #[error("invalid page URL: {0}")]
    Url(String),
}

/// What a settled page produced.
#[derive(Debug)]
pub struct PageOutcome {
    /// Serialized HTML after scripts ran.
    pub html: String,
    pub title: String,
    pub console: Vec<ConsoleMessage>,
    pub errors: Vec<ScriptError>,
    /// A `location.href = ...` or a form submission the page asked for but
    /// we did not follow.
    pub requested_navigation: Option<Navigation>,
    pub cookies: String,
    /// `document.cookie = ...` assignments, verbatim and in order, for a host
    /// that keeps a real cookie jar.
    pub cookie_writes: Vec<String>,
    /// Scripts that ran, and scripts skipped for lacking a body.
    pub scripts_run: usize,
    pub scripts_skipped: usize,
    /// Timer callbacks executed.
    pub timer_callbacks: u64,
    /// Subresource requests made.
    pub requests: usize,
    /// Virtual milliseconds the page reached.
    pub virtual_ms: i64,
    /// Real milliseconds spent.
    pub wall_ms: u128,
    /// True when the loop stopped on a limit rather than on quiescence.
    pub truncated: bool,
}

impl<N: NetworkProvider + 'static> Drop for Page<N> {
    fn drop(&mut self) {
        // The handles hold JS objects; they have to go while the runtime
        // that owns those objects is still here to free them.
        self.doc.clear_handles();
    }
}

/// Every `<script type="importmap">` in the document, merged.
///
/// Read before any script runs, as a browser does: a map added later by a
/// script is ignored there too.
fn import_map_of(doc: &Document, base: &Url) -> crate::modules::ImportMap {
    let mut merged = crate::modules::ImportMap::default();
    let root = doc.root();
    for id in doc.descendants(root) {
        let Some(el) = doc.element(id) else { continue };
        if el.local_name().as_ref() != "script" {
            continue;
        }
        let is_map = el
            .attr(&LocalName::from("type"))
            .is_some_and(|t| t.trim().eq_ignore_ascii_case("importmap"));
        if !is_map {
            continue;
        }
        if let Some(map) = crate::modules::ImportMap::parse(&doc.text_content(id), base) {
            merged.merge(map);
        }
    }
    merged
}

/// One `<script>` found in the document.
struct InlineScript {
    id: NodeId,
    /// Present when the script was never inlined, so it cannot run.
    src: Option<String>,
    /// `type="module"`, which needs module rather than script semantics.
    module: bool,
    body: String,
}

/// A page whose scripts have not run yet.
pub struct Page<N: NetworkProvider + 'static> {
    runtime: Runtime,
    context: Context,
    doc: SharedDoc,
    state: Shared,
    #[allow(dead_code)]
    net: Rc<N>,
    started: Instant,
    scripts_run: usize,
    scripts_skipped: usize,
}

impl<N: NetworkProvider + 'static> Page<N> {
    /// Parse `html` and build a JS context for it. Scripts do not run yet.
    pub fn new(html: &str, url: &str, limits: Limits, net: N) -> Result<Self, PageError> {
        let url = Url::parse(url).map_err(|e| PageError::Url(format!("{url}: {e}")))?;
        let parsed = mar_dom::parse_html(html);
        Page::with_document(parsed.document, url, limits, net)
    }

    pub fn with_document(
        document: Document,
        url: Url,
        limits: Limits,
        net: N,
    ) -> Result<Self, PageError> {
        let phase = Instant::now();
        let runtime = Runtime::new().map_err(|e| PageError::Engine(e.to_string()))?;
        // A ceiling turns runaway allocation into a JS exception instead of an
        // OOM kill, so one bad page cannot take the process with it.
        runtime.set_memory_limit(limits.memory_bytes);
        runtime.set_max_stack_size(limits.stack_bytes);
        // And a deadline the interpreter itself honours. The settle loop checks
        // the budget between callbacks, which is no help at all inside one:
        // `while (true) {}`, a catastrophic regex or a script that walks a
        // million nodes never returns, and the process waits forever. A page
        // fetched from the open web gets to do that on purpose, so the engine
        // has to be able to stop it mid-instruction.
        let deadline = Instant::now() + Duration::from_millis(limits.wall_ms);
        runtime.set_interrupt_handler(Some(Box::new(move || Instant::now() >= deadline)));
        let context = Context::full(&runtime).map_err(|e| PageError::Engine(e.to_string()))?;

        let doc = SharedDoc::new(document);
        let state = shared(PageState::new(url.clone(), limits));
        let net = Rc::new(net);

        // An `import` is resolved and fetched by the host, like every other
        // subresource. QuickJS asks for it synchronously, part-way through the
        // module that imported it, which is exactly what a blocking provider
        // and a virtual clock are built for. The page's import map, if it
        // wrote one, is what gives a bare specifier somewhere to resolve to.
        let import_map = import_map_of(&doc.borrow(), &url);
        runtime.set_loader(
            crate::modules::UrlResolver::with_import_map(url.clone(), import_map),
            crate::modules::UrlLoader::new(net.clone(), state.clone(), url.clone()),
        );

        context.with(|ctx| -> Result<(), PageError> {
            tracing::debug!(
                us = phase.elapsed().as_micros(),
                "phase: runtime and context"
            );
            // natives::install publishes `Node` first, so the prelude can
            // extend Node.prototype before any page script sees a node.
            natives::install(&ctx, &doc, &state, &net)
                .map_err(|e| PageError::Engine(format!("native bridge: {e}")))?;
            tracing::debug!(us = phase.elapsed().as_micros(), "phase: natives installed");
            run_prelude(&ctx).map_err(PageError::Engine)?;
            tracing::debug!(us = phase.elapsed().as_micros(), "phase: prelude evaluated");
            Ok(())
        })?;

        Ok(Page {
            runtime,
            context,
            doc,
            state,
            net,
            started: Instant::now(),
            scripts_run: 0,
            scripts_skipped: 0,
        })
    }

    /// The live document. Useful for inspecting the tree between phases.
    pub fn document(&self) -> &SharedDoc {
        &self.doc
    }

    pub fn state(&self) -> &Shared {
        &self.state
    }

    fn wall_ms(&self) -> u128 {
        self.started.elapsed().as_millis()
    }

    fn out_of_time(&self) -> bool {
        self.state.borrow().out_of_time()
    }

    /// Run every inline `<script>` in document order, then fire the ready
    /// events, then let timers and promises run until the page goes quiet.
    pub fn run(&mut self) -> PageOutcome {
        let phase = Instant::now();
        self.run_inline_scripts();
        tracing::debug!(us = phase.elapsed().as_micros(), "phase: inline scripts");
        self.state.borrow_mut().ready_state = "interactive";
        self.fire_ready();
        tracing::debug!(us = phase.elapsed().as_micros(), "phase: ready events");
        self.state.borrow_mut().ready_state = "complete";
        let truncated = self.settle();
        tracing::debug!(us = phase.elapsed().as_micros(), "phase: settled");
        let outcome = self.finish(truncated);
        tracing::debug!(us = phase.elapsed().as_micros(), "phase: finished");
        outcome
    }

    /// Execute a script source as the page would, recording any exception
    /// instead of propagating it: one broken script must not stop the others.
    ///
    /// Sloppy mode, because that is what a classic `<script>` is. Under strict
    /// mode an assignment to an undeclared name is a ReferenceError, and that
    /// is not a corner case: React's streaming markup bootstraps itself with
    /// bare `$RC = function(...)` assignments, so a strict engine loses every
    /// suspense boundary on every server-rendered React page. `with`, octal
    /// literals and duplicate parameter names are the same story on older code.
    pub fn eval_script(&mut self, source: &str, origin: &str) {
        let state = self.state.clone();
        let origin_owned = origin.to_owned();
        self.context.with(|ctx| {
            let mut options = rquickjs::context::EvalOptions::default();
            options.global = true;
            options.strict = false;
            // The filename shows up in stack traces, so an error points at the
            // script that raised it rather than at "eval_script".
            options.filename = Some(origin_owned.clone());
            if let Err(err) = ctx.eval_with_options::<(), _>(source, options).catch(&ctx) {
                state
                    .borrow_mut()
                    .record_error(origin_owned, format!("{err}"));
            }
        });
        self.scripts_run += 1;
    }

    /// Evaluate an expression and return it as JSON, for callers that want a
    /// value out of the page rather than its HTML.
    pub fn eval_json(&mut self, expression: &str) -> Result<String, String> {
        self.context.with(|ctx| {
            let wrapped =
                format!("JSON.stringify((function(){{ return ({expression}); }})()) ?? 'null'");
            ctx.eval::<String, _>(wrapped)
                .catch(&ctx)
                .map_err(|e| format!("{e}"))
        })
    }

    /// Evaluate `expression` and describe the result the way CDP does, keeping
    /// a handle when the value cannot be serialized.
    ///
    /// Returns the JSON of a `Runtime.RemoteObject`, or the error text.
    pub fn eval_remote(
        &mut self,
        expression: &str,
        by_value: bool,
        await_promise: bool,
    ) -> Result<String, String> {
        let source = format!("(function(){{ return ({expression}); }})()");
        self.describe_result(&source, by_value, await_promise)
    }

    /// Run `source`, optionally settling a promise, and describe the outcome.
    fn describe_result(
        &mut self,
        source: &str,
        by_value: bool,
        await_promise: bool,
    ) -> Result<String, String> {
        if !await_promise {
            let wrapped = format!(
                "JSON.stringify(__mar_describe({source}, {by_value})) ?? '{{\"type\":\"undefined\"}}'"
            );
            return self.context.with(|ctx| {
                ctx.eval::<String, _>(wrapped)
                    .catch(&ctx)
                    .map_err(|e| format!("{e}"))
            });
        }

        // Park the value, then let the loop run until it settles. Timers are
        // allowed to fire: an awaited value frequently depends on one.
        let slot: u32 = self.context.with(|ctx| {
            ctx.eval::<u32, _>(format!("__mar_await({source})"))
                .catch(&ctx)
                .map_err(|e| format!("{e}"))
        })?;

        let settled = self.settle_slot(slot, by_value)?;
        self.context.with(|ctx| {
            let _ = ctx.eval::<(), _>(format!("__mar_handle_release({slot})"));
        });
        Ok(settled)
    }

    /// Drive the loop until the parked slot settles, or the page runs out of
    /// budget. Returns the JSON the client should see.
    fn settle_slot(&mut self, slot: u32, by_value: bool) -> Result<String, String> {
        loop {
            let raw = self.context.with(|ctx| {
                ctx.eval::<String, _>(format!("__mar_settled({slot}, {by_value})"))
                    .catch(&ctx)
                    .map_err(|e| format!("{e}"))
            })?;

            let parsed: serde_json::Value =
                serde_json::from_str(&raw).map_err(|e| e.to_string())?;
            match parsed.get("state").and_then(|s| s.as_str()) {
                Some("fulfilled") => {
                    return Ok(parsed
                        .get("result")
                        .map(|r| r.to_string())
                        .unwrap_or_else(|| r#"{"type":"undefined"}"#.into()));
                }
                Some("rejected") => {
                    let description = parsed
                        .get("result")
                        .and_then(|r| r.get("description"))
                        .and_then(|d| d.as_str())
                        .unwrap_or("promise rejected")
                        .to_owned();
                    return Err(description);
                }
                Some("missing") => return Err("awaited value was released".into()),
                _ => {}
            }

            if self.out_of_time() {
                return Err("timed out awaiting a promise".into());
            }
            // Nothing settled it, so advance the loop by one step. When there
            // is nothing left to run, the promise never will settle.
            if !self.drain_microtasks() && !self.run_one_timer() {
                return Err("promise never settled".into());
            }
        }
    }

    /// Run the next due timer. Returns false when none is left.
    fn run_one_timer(&mut self) -> bool {
        let only_idle = self.state.borrow_mut().timers.next_due().is_none();
        let Some((callback, _)) = self.state.borrow_mut().timers.pop_due(only_idle) else {
            return false;
        };
        self.invoke(callback);
        true
    }

    /// Call a function declaration against a retained handle, with arguments
    /// that may themselves be handles.
    ///
    /// `this_handle` and each `Some(id)` in `arg_handles` name a value the page
    /// is still holding; `None` entries take the matching literal from
    /// `arg_values`, which is a JSON array.
    pub fn call_on_handle(
        &mut self,
        this_handle: Option<u32>,
        declaration: &str,
        arg_handles: &[Option<u32>],
        arg_values: &str,
        by_value: bool,
        await_promise: bool,
    ) -> Result<String, String> {
        let this_expr = match this_handle {
            Some(id) => format!("__mar_handle_get({id})"),
            None => "globalThis".to_owned(),
        };
        // Build the argument list: a handle resolves through the registry, a
        // literal comes from the JSON array by position.
        let args: Vec<String> = arg_handles
            .iter()
            .enumerate()
            .map(|(i, handle)| match handle {
                Some(id) => format!("__mar_handle_get({id})"),
                None => format!("__mar_args[{i}]"),
            })
            .collect();

        let source = format!(
            "(function(){{ const __mar_args = {arg_values}; \
             const __mar_fn = ({declaration}); \
             return __mar_fn.apply({this_expr}, [{}]); }})()",
            args.join(", ")
        );
        self.describe_result(&source, by_value, await_promise)
    }

    /// Hand out a handle for a node the DOM layer resolved.
    pub fn handle_for_node(&mut self, node: NodeId) -> Result<u32, String> {
        // The node is looked up through the same registry the DOM bindings use,
        // so the client's handle points at the live node, not a copy.
        let expression = format!("__mar_handle_put(__mar_node_by_id({}))", node.as_u32());
        self.context.with(|ctx| {
            ctx.eval::<u32, _>(expression)
                .catch(&ctx)
                .map_err(|e| format!("{e}"))
        })
    }

    /// Enumerate a handle's own properties, as a JSON array of CDP
    /// `PropertyDescriptor` objects.
    pub fn handle_properties(&mut self, id: u32, own_only: bool) -> Result<String, String> {
        self.context.with(|ctx| {
            ctx.eval::<String, _>(format!(
                "JSON.stringify(__mar_handle_properties({id}, {own_only})) ?? '[]'"
            ))
            .catch(&ctx)
            .map_err(|e| format!("{e}"))
        })
    }

    /// The arena node a handle points at, if it points at a node at all.
    pub fn node_of_handle(&mut self, id: u32) -> Option<NodeId> {
        let raw = self.context.with(|ctx| {
            ctx.eval::<i64, _>(format!(
                "(function(){{ const v = __mar_handle_get({id}); \
                 return (v && typeof v.marNodeId === 'number') ? v.marNodeId : 0; }})()"
            ))
            .ok()
        })?;
        NodeId::from_u32(u32::try_from(raw).ok()?)
    }

    /// Forget a handle the client released.
    pub fn release_handle(&mut self, id: u32) {
        self.context.with(|ctx| {
            let _ = ctx.eval::<(), _>(format!("__mar_handle_release({id})"));
        });
    }

    fn run_inline_scripts(&mut self) {
        // Snapshot the script list first: a script that appends more scripts
        // must not extend the loop it is running inside.
        let scripts: Vec<InlineScript> = {
            let doc = self.doc.borrow();
            let root = doc.root();
            doc.descendants(root)
                .filter_map(|id| {
                    let el = doc.element(id)?;
                    if el.local_name().as_ref() != "script" {
                        return None;
                    }
                    // Skip anything that is not classic executable JS.
                    let ty = el.attr(&LocalName::from("type")).unwrap_or("");
                    let executable = ty.is_empty()
                        || ty.eq_ignore_ascii_case("text/javascript")
                        || ty.eq_ignore_ascii_case("application/javascript")
                        || ty.eq_ignore_ascii_case("module");
                    if !executable {
                        return None;
                    }
                    Some(InlineScript {
                        id,
                        src: el.attr(&LocalName::from("src")).map(str::to_owned),
                        module: ty.eq_ignore_ascii_case("module"),
                        body: doc.text_content(id),
                    })
                })
                .collect()
        };

        for script in scripts {
            if self.out_of_time() {
                self.scripts_skipped += 1;
                continue;
            }
            // A script with a `src` and no body was not inlined by the host,
            // deliberately or otherwise. That is a policy decision made
            // elsewhere, so it is counted, not reported as a page error.
            if script.body.trim().is_empty() {
                self.scripts_skipped += 1;
                continue;
            }
            // `document.currentScript` is the running script, and a bundler
            // reads its `src` to find its own chunks. A module is deliberately
            // excluded: in a browser it is null there, and code that has both
            // paths picks the `import.meta.url` one when it is.
            self.state.borrow_mut().current_script = (!script.module).then_some(script.id);

            // A script's name is its URL, because that is what its own
            // imports resolve against and what an error should point at. The
            // host leaves `src` in place when it inlines one, so the body knows
            // where it came from; an inline script is named for its node.
            let page_url = self.state.borrow().url.clone();
            let source_url = script
                .src
                .as_deref()
                .and_then(|src| page_url.join(src).ok())
                .map(|u| u.to_string());
            if script.module {
                let origin = source_url.unwrap_or_else(|| page_url.to_string());
                self.eval_module(&script.body, &origin);
            } else {
                let origin =
                    source_url.unwrap_or_else(|| format!("inline script #{}", script.id.as_u32()));
                self.eval_script(&script.body, &origin);
            }

            // Null again once the script returns: a callback that runs later
            // is not "during" any script, and code that caches currentScript
            // at module scope has already read it.
            self.state.borrow_mut().current_script = None;
        }
    }

    /// Evaluate a `type="module"` script.
    ///
    /// Module syntax (`import`, `export`, top-level `await`) is a syntax error
    /// in script mode, so a bundled page evaluated as a classic script fails
    /// on its first line and renders nothing.
    fn eval_module(&mut self, source: &str, origin: &str) {
        let state = self.state.clone();
        let origin_owned = origin.to_owned();
        self.context.with(|ctx| {
            let declared = Module::declare(ctx.clone(), origin_owned.clone(), source).catch(&ctx);
            match declared {
                Ok(module) => {
                    crate::modules::set_import_meta(&module, &origin_owned);
                    match module.eval().catch(&ctx) {
                        // The body of a module runs inside a promise. A throw on
                        // its first line rejects that promise instead of raising
                        // here, so the promise has to be watched or the failure is
                        // silent — and a dead application module then looks exactly
                        // like a page that deliberately rendered nothing.
                        Ok((_, promise)) => {
                            let watch: Result<rquickjs::Function, _> =
                                ctx.globals().get("__mar_watch_module");
                            if let Ok(watch) = watch {
                                let _ = watch.call::<_, ()>((promise, origin_owned.clone()));
                            }
                        }
                        Err(e) => {
                            state
                                .borrow_mut()
                                .record_error(origin_owned, format!("{e}"));
                        }
                    }
                }
                Err(e) => {
                    state
                        .borrow_mut()
                        .record_error(origin_owned, format!("module compile failed: {e}"));
                }
            }
        });
        self.scripts_run += 1;
    }

    fn fire_ready(&mut self) {
        let state = self.state.clone();
        self.context.with(|ctx| {
            let result: rquickjs::Result<()> = (|| {
                let f: Function = ctx.globals().get("__mar_fire_ready")?;
                f.call::<_, ()>(())
            })();
            if let Err(e) = result.catch(&ctx) {
                state
                    .borrow_mut()
                    .record_error("ready events", format!("{e}"));
            }
        });
    }

    /// Hand one finished request back to the page.
    ///
    /// `block` waits for the next one; without it this only takes what has
    /// already landed. Returns false when there was nothing to deliver.
    fn deliver_response(&mut self, block: bool) -> bool {
        let received = {
            let state = self.state.borrow();
            if state.inflight == 0 {
                return false;
            }
            if block {
                // Bounded: a request that outlives the page's budget is not
                // worth the page's remaining time.
                let left = (state.limits.wall_ms as u128)
                    .saturating_sub(state.started.elapsed().as_millis());
                state
                    .responses
                    .recv_timeout(std::time::Duration::from_millis((left as u64).max(1)))
                    .ok()
            } else {
                state.responses.try_recv().ok()
            }
        };
        let Some((id, result)) = received else {
            if block {
                // Timed out waiting: nothing more will arrive in time, so stop
                // counting on it rather than spinning.
                self.state.borrow_mut().inflight = 0;
            }
            return false;
        };
        {
            let mut state = self.state.borrow_mut();
            // Saturating: the loop zeroes this when it stops waiting, and a
            // late arrival must not take the count below the floor.
            state.inflight = state.inflight.saturating_sub(1);
        }

        let state = self.state.clone();
        self.context.with(|ctx| {
            let deliver: rquickjs::Result<Function> = ctx.globals().get("__mar_deliver");
            let Ok(deliver) = deliver else { return };
            let payload = match natives::response_object(&ctx, result) {
                Ok(o) => o,
                Err(_) => return,
            };
            if let Err(e) = deliver.call::<_, ()>((id, payload)).catch(&ctx) {
                state
                    .borrow_mut()
                    .record_error("response delivery", format!("{e}"));
            }
        });
        true
    }

    /// Drain microtasks and timers until nothing is left to run.
    ///
    /// Returns true if a limit stopped the loop rather than quiescence. The
    /// virtual clock means "wait 5 seconds" costs nothing, so a page that
    /// staggers work over its first few seconds still settles immediately.
    fn settle(&mut self) -> bool {
        loop {
            if self.out_of_time() {
                return true;
            }

            // Promises first: a resolved fetch must be visible before the next
            // timer runs, as it would be in a real event loop.
            if self.drain_microtasks() {
                continue;
            }

            // Then anything the network has already answered.
            if self.deliver_response(false) {
                continue;
            }

            let (has_timer, budget_left) = {
                let mut s = self.state.borrow_mut();
                let fired = s.timers.fired();
                let max = s.limits.max_timer_callbacks;
                (s.timers.has_pending(), fired < max)
            };
            if !has_timer {
                // No timers, but the page is waiting on the network: that is
                // not a settled page, it is a page mid-request. Wait for it,
                // exactly as an event loop would.
                if self.deliver_response(true) {
                    continue;
                }
                return false;
            }
            if !budget_left {
                return true;
            }

            // Idle callbacks only run once they are the sole thing left.
            let only_idle = self.state.borrow_mut().timers.next_due().is_none();
            let Some((callback, _id)) = self.state.borrow_mut().timers.pop_due(only_idle) else {
                return false;
            };
            self.invoke(callback);
        }
    }

    /// Run pending jobs. Returns true if any ran.
    fn drain_microtasks(&mut self) -> bool {
        let mut ran = false;
        loop {
            match self.runtime.execute_pending_job() {
                Ok(true) => {
                    ran = true;
                    if self.out_of_time() {
                        return ran;
                    }
                }
                Ok(false) => return ran,
                Err(e) => {
                    // A job that threw is reported and the loop continues; the
                    // rest of the page is usually still worth reading.
                    self.state
                        .borrow_mut()
                        .record_error("microtask", format!("{e:?}"));
                    ran = true;
                }
            }
        }
    }

    fn invoke(&mut self, callback: Persistent<Function<'static>>) {
        let state = self.state.clone();
        self.context.with(|ctx: Ctx| {
            let f = callback.clone().restore(&ctx);
            match f {
                Ok(f) => {
                    if let Err(e) = f.call::<_, ()>(()).catch(&ctx) {
                        state.borrow_mut().record_error("timer", format!("{e}"));
                    }
                }
                Err(e) => {
                    state
                        .borrow_mut()
                        .record_error("timer", format!("lost callback: {e}"));
                }
            }
        });
    }

    fn finish(&mut self, truncated: bool) -> PageOutcome {
        self.state.borrow_mut().timers.clear();
        // Give QuickJS a chance to release the DOM handles before we read the
        // document, so the outcome reflects a settled heap.
        self.runtime.run_gc();

        let doc = self.doc.borrow();
        let html = mar_dom::document_html(&doc);
        let title = doc
            .head()
            .and_then(|h| {
                doc.children(h).find(|&c| {
                    doc.element(c)
                        .is_some_and(|e| e.local_name().as_ref() == "title")
                })
            })
            .map(|t| doc.text_content(t).trim().to_owned())
            .unwrap_or_default();
        drop(doc);

        let s = self.state.borrow();
        PageOutcome {
            html,
            title,
            console: s.console.clone(),
            errors: s.errors.clone(),
            requested_navigation: s.requested_navigation.clone(),
            cookies: s.cookies.clone(),
            cookie_writes: s.cookie_writes.clone(),
            scripts_run: self.scripts_run,
            scripts_skipped: self.scripts_skipped,
            timer_callbacks: s.timers.fired(),
            requests: s.request_count,
            virtual_ms: s.timers.now_ms(),
            wall_ms: self.wall_ms(),
            truncated,
        }
    }
}
