//! A page: a document, a JS context, and the loop that runs one until it stops
//! changing.

use crate::dom::SharedDoc;
use crate::natives;
use crate::net::NetworkProvider;
use crate::state::{ConsoleMessage, Limits, PageState, ScriptError, Shared, shared};
use mar_dom::{Document, LocalName, NodeId};
use rquickjs::{CatchResultExt, Context, Ctx, Function, Module, Persistent, Runtime};
use std::rc::Rc;
use std::time::Instant;
use url::Url;

const PRELUDE: &str = include_str!("prelude.js");

#[derive(Debug, thiserror::Error)]
pub enum PageError {
    #[error("javascript engine error: {0}")]
    Engine(String),
    #[error("invalid page URL: {0}")]
    Url(String),
}

/// What a settled page produced.
#[derive(Debug)]
pub struct PageOutcome {
    /// Serialized HTML after scripts ran.
    pub html: String,
    pub title: String,
    pub console: Vec<ConsoleMessage>,
    pub errors: Vec<ScriptError>,
    /// A `location.href = ...` the page asked for but we did not follow.
    pub requested_navigation: Option<String>,
    pub cookies: String,
    /// Scripts that ran, and scripts skipped for lacking a body.
    pub scripts_run: usize,
    pub scripts_skipped: usize,
    /// Timer callbacks executed.
    pub timer_callbacks: u64,
    /// Subresource requests made.
    pub requests: usize,
    /// Virtual milliseconds the page reached.
    pub virtual_ms: i64,
    /// Real milliseconds spent.
    pub wall_ms: u128,
    /// True when the loop stopped on a limit rather than on quiescence.
    pub truncated: bool,
}

/// One `<script>` found in the document.
struct InlineScript {
    id: NodeId,
    /// Present when the script was never inlined, so it cannot run.
    src: Option<String>,
    /// `type="module"`, which needs module rather than script semantics.
    module: bool,
    body: String,
}

/// A page whose scripts have not run yet.
pub struct Page<N: NetworkProvider + 'static> {
    runtime: Runtime,
    context: Context,
    doc: SharedDoc,
    state: Shared,
    #[allow(dead_code)]
    net: Rc<N>,
    started: Instant,
    scripts_run: usize,
    scripts_skipped: usize,
}

impl<N: NetworkProvider + 'static> Page<N> {
    /// Parse `html` and build a JS context for it. Scripts do not run yet.
    pub fn new(html: &str, url: &str, limits: Limits, net: N) -> Result<Self, PageError> {
        let url = Url::parse(url).map_err(|e| PageError::Url(format!("{url}: {e}")))?;
        let parsed = mar_dom::parse_html(html);
        Page::with_document(parsed.document, url, limits, net)
    }

    pub fn with_document(
        document: Document,
        url: Url,
        limits: Limits,
        net: N,
    ) -> Result<Self, PageError> {
        let runtime = Runtime::new().map_err(|e| PageError::Engine(e.to_string()))?;
        // A ceiling turns runaway allocation into a JS exception instead of an
        // OOM kill, so one bad page cannot take the process with it.
        runtime.set_memory_limit(limits.memory_bytes);
        runtime.set_max_stack_size(limits.stack_bytes);
        let context = Context::full(&runtime).map_err(|e| PageError::Engine(e.to_string()))?;

        let doc = SharedDoc::new(document);
        let state = shared(PageState::new(url, limits));
        let net = Rc::new(net);

        context.with(|ctx| -> Result<(), PageError> {
            // natives::install publishes `Node` first, so the prelude can
            // extend Node.prototype before any page script sees a node.
            natives::install(&ctx, &doc, &state, &net)
                .map_err(|e| PageError::Engine(format!("native bridge: {e}")))?;
            // catch() turns the opaque "Exception generated by QuickJS" into
            // the actual message and stack.
            ctx.eval::<(), _>(PRELUDE)
                .catch(&ctx)
                .map_err(|e| PageError::Engine(format!("prelude: {e}")))?;
            Ok(())
        })?;

        Ok(Page {
            runtime,
            context,
            doc,
            state,
            net,
            started: Instant::now(),
            scripts_run: 0,
            scripts_skipped: 0,
        })
    }

    /// The live document. Useful for inspecting the tree between phases.
    pub fn document(&self) -> &SharedDoc {
        &self.doc
    }

    pub fn state(&self) -> &Shared {
        &self.state
    }

    fn wall_ms(&self) -> u128 {
        self.started.elapsed().as_millis()
    }

    fn out_of_time(&self) -> bool {
        self.wall_ms() >= self.state.borrow().limits.wall_ms as u128
    }

    /// Run every inline `<script>` in document order, then fire the ready
    /// events, then let timers and promises run until the page goes quiet.
    pub fn run(&mut self) -> PageOutcome {
        self.run_inline_scripts();
        self.state.borrow_mut().ready_state = "interactive";
        self.fire_ready();
        self.state.borrow_mut().ready_state = "complete";
        let truncated = self.settle();
        self.finish(truncated)
    }

    /// Execute a script source as the page would, recording any exception
    /// instead of propagating it: one broken script must not stop the others.
    pub fn eval_script(&mut self, source: &str, origin: &str) {
        let state = self.state.clone();
        let origin_owned = origin.to_owned();
        self.context.with(|ctx| {
            if let Err(err) = ctx.eval::<(), _>(source).catch(&ctx) {
                state
                    .borrow_mut()
                    .record_error(origin_owned, format!("{err}"));
            }
        });
        self.scripts_run += 1;
    }

    /// Evaluate an expression and return it as JSON, for callers that want a
    /// value out of the page rather than its HTML.
    pub fn eval_json(&mut self, expression: &str) -> Result<String, String> {
        self.context.with(|ctx| {
            let wrapped = format!(
                "JSON.stringify((function(){{ return ({expression}); }})()) ?? 'null'"
            );
            ctx.eval::<String, _>(wrapped)
                .catch(&ctx)
                .map_err(|e| format!("{e}"))
        })
    }

    fn run_inline_scripts(&mut self) {
        // Snapshot the script list first: a script that appends more scripts
        // must not extend the loop it is running inside.
        let scripts: Vec<InlineScript> = {
            let doc = self.doc.borrow();
            let root = doc.root();
            doc.descendants(root)
                .filter_map(|id| {
                    let el = doc.element(id)?;
                    if el.local_name().as_ref() != "script" {
                        return None;
                    }
                    // Skip anything that is not classic executable JS.
                    let ty = el.attr(&LocalName::from("type")).unwrap_or("");
                    let executable = ty.is_empty()
                        || ty.eq_ignore_ascii_case("text/javascript")
                        || ty.eq_ignore_ascii_case("application/javascript")
                        || ty.eq_ignore_ascii_case("module");
                    if !executable {
                        return None;
                    }
                    Some(InlineScript {
                        id,
                        src: el.attr(&LocalName::from("src")).map(str::to_owned),
                        module: ty.eq_ignore_ascii_case("module"),
                        body: doc.text_content(id),
                    })
                })
                .collect()
        };

        for script in scripts {
            if self.out_of_time() {
                self.scripts_skipped += 1;
                continue;
            }
            // A script that still has a `src` was not inlined by the host,
            // deliberately or otherwise. That is a policy decision made
            // elsewhere, so it is counted, not reported as a page error.
            if script.src.is_some() || script.body.trim().is_empty() {
                self.scripts_skipped += 1;
                continue;
            }
            let origin = format!("inline script #{}", script.id.as_u32());
            if script.module {
                self.eval_module(&script.body, &origin);
            } else {
                self.eval_script(&script.body, &origin);
            }
        }
    }

    /// Evaluate a `type="module"` script.
    ///
    /// Module syntax (`import`, `export`, top-level `await`) is a syntax error
    /// in script mode, so a bundled page evaluated as a classic script fails
    /// on its first line and renders nothing.
    fn eval_module(&mut self, source: &str, origin: &str) {
        let state = self.state.clone();
        let origin_owned = origin.to_owned();
        self.context.with(|ctx| {
            let declared = Module::declare(ctx.clone(), origin_owned.clone(), source).catch(&ctx);
            match declared {
                Ok(module) => {
                    // A module returns a promise; rejections surface when the
                    // settle loop drains pending jobs.
                    if let Err(e) = module.eval().catch(&ctx) {
                        state
                            .borrow_mut()
                            .record_error(origin_owned, format!("{e}"));
                    }
                }
                Err(e) => {
                    state
                        .borrow_mut()
                        .record_error(origin_owned, format!("module compile failed: {e}"));
                }
            }
        });
        self.scripts_run += 1;
    }

    fn fire_ready(&mut self) {
        let state = self.state.clone();
        self.context.with(|ctx| {
            let result: rquickjs::Result<()> = (|| {
                let f: Function = ctx.globals().get("__mar_fire_ready")?;
                f.call::<_, ()>(())
            })();
            if let Err(e) = result.catch(&ctx) {
                state.borrow_mut().record_error("ready events", format!("{e}"));
            }
        });
    }

    /// Drain microtasks and timers until nothing is left to run.
    ///
    /// Returns true if a limit stopped the loop rather than quiescence. The
    /// virtual clock means "wait 5 seconds" costs nothing, so a page that
    /// staggers work over its first few seconds still settles immediately.
    fn settle(&mut self) -> bool {
        loop {
            if self.out_of_time() {
                return true;
            }

            // Promises first: a resolved fetch must be visible before the next
            // timer runs, as it would be in a real event loop.
            if self.drain_microtasks() {
                continue;
            }

            let (has_timer, budget_left) = {
                let mut s = self.state.borrow_mut();
                let fired = s.timers.fired();
                let max = s.limits.max_timer_callbacks;
                (s.timers.has_pending(), fired < max)
            };
            if !has_timer {
                return false;
            }
            if !budget_left {
                return true;
            }

            // Idle callbacks only run once they are the sole thing left.
            let only_idle = self.state.borrow_mut().timers.next_due().is_none();
            let Some((callback, _id)) = self.state.borrow_mut().timers.pop_due(only_idle) else {
                return false;
            };
            self.invoke(callback);
        }
    }

    /// Run pending jobs. Returns true if any ran.
    fn drain_microtasks(&mut self) -> bool {
        let mut ran = false;
        loop {
            match self.runtime.execute_pending_job() {
                Ok(true) => {
                    ran = true;
                    if self.out_of_time() {
                        return ran;
                    }
                }
                Ok(false) => return ran,
                Err(e) => {
                    // A job that threw is reported and the loop continues; the
                    // rest of the page is usually still worth reading.
                    self.state
                        .borrow_mut()
                        .record_error("microtask", format!("{e:?}"));
                    ran = true;
                }
            }
        }
    }

    fn invoke(&mut self, callback: Persistent<Function<'static>>) {
        let state = self.state.clone();
        self.context.with(|ctx: Ctx| {
            let f = callback.clone().restore(&ctx);
            match f {
                Ok(f) => {
                    if let Err(e) = f.call::<_, ()>(()).catch(&ctx) {
                        state.borrow_mut().record_error("timer", format!("{e}"));
                    }
                }
                Err(e) => {
                    state
                        .borrow_mut()
                        .record_error("timer", format!("lost callback: {e}"));
                }
            }
        });
    }

    fn finish(&mut self, truncated: bool) -> PageOutcome {
        self.state.borrow_mut().timers.clear();
        // Give QuickJS a chance to release the DOM handles before we read the
        // document, so the outcome reflects a settled heap.
        self.runtime.run_gc();

        let doc = self.doc.borrow();
        let html = mar_dom::document_html(&doc);
        let title = doc
            .head()
            .and_then(|h| {
                doc.children(h).find(|&c| {
                    doc.element(c)
                        .is_some_and(|e| e.local_name().as_ref() == "title")
                })
            })
            .map(|t| doc.text_content(t).trim().to_owned())
            .unwrap_or_default();
        drop(doc);

        let s = self.state.borrow();
        PageOutcome {
            html,
            title,
            console: s.console.clone(),
            errors: s.errors.clone(),
            requested_navigation: s.requested_navigation.clone(),
            cookies: s.cookies.clone(),
            scripts_run: self.scripts_run,
            scripts_skipped: self.scripts_skipped,
            timer_callbacks: s.timers.fired(),
            requests: s.request_count,
            virtual_ms: s.timers.now_ms(),
            wall_ms: self.wall_ms(),
            truncated,
        }
    }
}
